# Generated by Django 5.2.4 on 2025-07-14 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('reward_router', models.CharField(max_length=255)),
                ('redeem_router', models.CharField(max_length=255)),
                ('owner', models.CharField(max_length=255)),
                ('private_key', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('token_name', models.CharField(max_length=255)),
                ('token_price', models.DecimalField(decimal_places=4, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, unique=True)),
                ('private_key', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RedeemEvent',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='analytics.event')),
                ('type', models.CharField(default='redeem', max_length=10)),
                ('business', models.CharField(max_length=255)),
                ('user', models.CharField(max_length=255)),
                ('token', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('analytics.event',),
        ),
        migrations.CreateModel(
            name='RewardEvent',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='analytics.event')),
                ('type', models.CharField(default='reward', max_length=10)),
                ('business', models.CharField(max_length=255)),
                ('user', models.CharField(max_length=255)),
                ('token', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('analytics.event',),
        ),
        migrations.CreateModel(
            name='SwapEvent',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='analytics.event')),
                ('type', models.CharField(default='swap', max_length=10)),
                ('from_user', models.CharField(max_length=255)),
                ('from_token', models.CharField(max_length=100)),
                ('from_amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('from_business', models.CharField(max_length=255)),
                ('to_user', models.CharField(max_length=255)),
                ('to_token', models.CharField(max_length=100)),
                ('to_amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('to_business', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('analytics.event',),
        ),
        migrations.CreateModel(
            name='TransferEvent',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='analytics.event')),
                ('type', models.CharField(default='transfer', max_length=10)),
                ('business', models.CharField(max_length=255)),
                ('token', models.CharField(max_length=100)),
                ('from_address', models.CharField(max_length=255)),
                ('to_address', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('analytics.event',),
        ),
    ]
