# Generated by Django 5.2.4 on 2025-05-19 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='token',
            field=models.CharField(max_length=255),
        ),
    ]
