# Generated by Django 5.2.4 on 2025-07-14 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_alter_business_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='redeemevent',
            name='type',
        ),
        migrations.RemoveField(
            model_name='rewardevent',
            name='type',
        ),
        migrations.RemoveField(
            model_name='swapevent',
            name='type',
        ),
        migrations.RemoveField(
            model_name='transferevent',
            name='from_address',
        ),
        migrations.RemoveField(
            model_name='transferevent',
            name='to_address',
        ),
        migrations.RemoveField(
            model_name='transferevent',
            name='type',
        ),
        migrations.AddField(
            model_name='transferevent',
            name='from_user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='transfers_out', to='analytics.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transferevent',
            name='to_user',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='transfers_in', to='analytics.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='redeemevent',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.business'),
        ),
        migrations.AlterField(
            model_name='redeemevent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.user'),
        ),
        migrations.AlterField(
            model_name='rewardevent',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.business'),
        ),
        migrations.AlterField(
            model_name='rewardevent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.user'),
        ),
        migrations.AlterField(
            model_name='swapevent',
            name='from_business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swaps_out', to='analytics.business'),
        ),
        migrations.AlterField(
            model_name='swapevent',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swaps_out', to='analytics.user'),
        ),
        migrations.AlterField(
            model_name='swapevent',
            name='to_business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swaps_in', to='analytics.business'),
        ),
        migrations.AlterField(
            model_name='swapevent',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swaps_in', to='analytics.user'),
        ),
        migrations.AlterField(
            model_name='transferevent',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.business'),
        ),
    ]
